# Generated by Django 3.2 on 2023-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('adult', 'adult'), ("children's", "children's"), ('Irish', 'Gaelige'), ('poetry', 'poetry'), ('fiction', 'fiction'), ('non-fiction', 'non-fiction')], max_length=20)),
                ('quarter', models.CharField(choices=[('Spring', 'Earrach'), ('Summer', 'Samhradh'), ('Autumn', 'Fómhar'), ('Winter', 'Geimhreadh')], max_length=10)),
                ('sku', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('length', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distributor', models.CharField(max_length=100)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['quarter'],
            },
        ),
    ]
