# Generated by Django 3.2 on 2023-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='audience',
            field=models.CharField(choices=[('adult', 'adult'), ("children's", "children's")], default='adult', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('poetry', 'poetry'), ('fiction', 'fiction'), ('non-fiction', 'non-fiction')], default='fiction', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Irish', 'Gaelige'), ('ENG', 'English')], default='ENG', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
