# Generated by Django 3.2 on 2023-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230317_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='audience',
            field=models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Irish', 'Gaelige'), ('English', 'English')], default='English', max_length=10),
        ),
    ]
