# Generated by Django 3.2 on 2023-03-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20230317_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quarter',
            field=models.CharField(choices=[('Earrach', 'spring'), ('Samhradh', 'summer'), ('Fómhar', 'autumn'), ('Geimhreadh', 'winter')], max_length=10),
        ),
    ]
