# Generated by Django 3.2 on 2023-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('hardback', 'hardback'), ('paperback', 'paperback'), ('chapbook', 'chapbook')], default=None, max_length=20),
        ),
    ]
