# Generated by Django 3.2 on 2023-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='length',
            new_name='pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='distributor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='quarter',
            field=models.CharField(choices=[('Earrach 2023', 'Spring 2023'), ('Samhradh 2023', 'Summer 2023'), ('Fómhar 2023', 'Autumn 2023'), ('Geimhreadh 2023', 'Winter 2023')], max_length=100),
        ),
    ]
