# Generated by Django 3.2 on 2023-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20230317_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(max_length=13, unique=True),
        ),
    ]
