# Generated by Django 3.2 on 2023-03-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(unique=True),
        ),
    ]
