# Generated by Django 3.2 on 2023-03-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20230317_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(default=None),
        ),
    ]
