# Generated by Django 3.2 on 2023-03-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_pub_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.DecimalField(blank=True, decimal_places=0, default='2023', max_digits=4, null=True),
        ),
    ]
