# Generated by Django 3.2 on 2023-03-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_pub_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_year',
            new_name='year',
        ),
    ]
