# Generated by Django 3.2 on 2023-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_rename_pub_year_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default='2023'),
        ),
    ]
