# Generated by Django 3.2 on 2023-03-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20230317_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
