# Generated by Django 3.2 on 2023-03-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_pub_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_year',
        ),
    ]
