# Generated by Django 3.2 on 2023-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_remove_book_pub_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
