# Generated by Django 3.2 on 2023-03-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name1', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name1', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Featured_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('quarter', models.CharField(choices=[('Earrach 2023', 'Spring 2023'), ('Samhradh 2023', 'Summer 2023'), ('Fómhar 2023', 'Autumn 2023'), ('Geimhreadh 2023', 'Winter 2023')], max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Featured_Products',
                'ordering': ['quarter'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Earrach 2023', 'Spring 2023'), ('Samhradh 2023', 'Summer 2023'), ('Fómhar 2023', 'Autumn 2023'), ('Geimhreadh 2023', 'Winter 2023')], max_length=100)),
                ('audience', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=10)),
                ('language', models.CharField(choices=[('Irish', 'Gaelige'), ('English', 'English')], default='English', max_length=10)),
                ('genre', models.CharField(choices=[('poetry', 'poetry'), ('fiction', 'fiction'), ('non-fiction', 'non-fiction')], default='fiction', max_length=20)),
                ('format', models.CharField(choices=[('hardback', 'hardback'), ('paperback', 'paperback'), ('chapbook', 'chapbook')], default=None, max_length=20)),
                ('sku', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('isbn', models.IntegerField()),
                ('title', models.CharField(max_length=250, unique=True)),
                ('pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('publication_year', models.PositiveSmallIntegerField(default=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distributor', models.CharField(default='Unknown', max_length=100)),
                ('blurb', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['quarter'],
            },
        ),
    ]
