# Generated by Django 3.2 on 2023-04-04 10:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name1', models.CharField(blank=True, default=' ', max_length=40)),
                ('last_name1', models.CharField(blank=True, default=' ', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Featured_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('quarter', models.CharField(choices=[('Earrach 2023', 'Spring 2023'), ('Samhradh 2023', 'Summer 2023'), ('Fómhar 2023', 'Autumn 2023'), ('Geimhreadh 2023', 'Winter 2023')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('manufacturer', models.CharField(max_length=100)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('advert_image1', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image1_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('advert_image2', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image2_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('website', models.URLField(blank=True, db_index=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Featured Products',
                'ordering': ['quarter'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('poetry', 'poetry'), ('fiction', 'fiction'), ('non-fiction', 'non-fiction')], default='fiction', max_length=20)),
                ('quarter', models.CharField(choices=[('Earrach 2023', 'Spring 2023'), ('Samhradh 2023', 'Summer 2023'), ('Fómhar 2023', 'Autumn 2023'), ('Geimhreadh 2023', 'Winter 2023')], max_length=100)),
                ('audience', models.CharField(choices=[('adult', 'adult'), ('children', 'children')], default='adult', max_length=10)),
                ('language', models.CharField(choices=[('Irish', 'Gaelige'), ('English', 'English')], default='English', max_length=10)),
                ('format', models.CharField(choices=[('hardback', 'hardback'), ('paperback', 'paperback'), ('chapbook', 'chapbook')], default=None, max_length=20)),
                ('sku', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('publication_year', models.PositiveSmallIntegerField(default=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distributor', models.CharField(default='Unknown', max_length=100)),
                ('in_stock', models.BooleanField(default=True)),
                ('blurb', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['quarter'],
            },
        ),
    ]
