# Generated by Django 3.2 on 2023-03-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featured_product',
            options={'ordering': ['quarter'], 'verbose_name_plural': 'Featured Products'},
        ),
    ]
