# Generated by Django 3.2 on 2023-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230324_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(blank=True, max_length=250, null=True),
        ),
    ]
