# Generated by Django 3.2 on 2023-03-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
