# Generated by Django 3.2 on 2023-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230401_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_product',
            name='extra_image1',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='featured_product',
            name='extra_image2',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
