# Generated by Django 3.2 on 2023-04-01 19:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230401_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured_product',
            old_name='extra_image1',
            new_name='extra_image1_url',
        ),
        migrations.RenameField(
            model_name='featured_product',
            old_name='extra_image2',
            new_name='extra_image2_url',
        ),
        migrations.AddField(
            model_name='featured_product',
            name='featured_image1',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='featured_product',
            name='featured_image2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
