# Generated by Django 3.2 on 2023-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230401_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_product',
            name='website',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
